teleirc.js
* Showing text descriptions of non-text messages (eg. images, stickers, videos).
* Show "@*nick*" mention whenever it's replying another message (on Telegram).
=> Show descriptions of non-text messages

teleirc.js
Add support for irc notice ie. /me command.
=> Add support for irc notice

config.js.example, tg.js
I have programmed to can possible change the name of who sended the message on telegram to irc.
=> Configurable format for show who sended the message

config.js.example, tg.js
@fczuardi and I altered the lines of the code about the show the user with send the messages on the telegram to show his username too.
=> Show the username of telegram user with sended the message

config.defaults.js, irc.js
=> IRC perform

README.md, commands.txt, irc.js, tg.js
=> /names command to list IRC users

teleirc.js
Fixes #23, but a better solution would be desired
=> dummy functions for sendTo.irc/tg until they are initialized

tg.js
Add support to other media types than pic to be linked to irc.
=> Link all media to irc

package.json
=> update dependencies to latest versions

config.defaults.js, nickcolor.js, package.json, tg.js
I was running into readability problems when I had 5 or 6 users speaking on telegram.
So I added this colorizing feature.
=> Colorized Nicks for IRC users

config.defaults.js, tg.js
When replying to an IRC message from the bot, use the IRC user as the nick.
=> Improved replies

tg.js
Video and images may have a caption, append them to the URL if they exist.
=> Media captions

tg.js
Currently just keeps known users in memory. Could be stored in a file, but I think that is unnecessary as it will be long running, and most mentions will be in reply to something. Until botapi lets us query the users in a channel this will have to be the best way.
=> Add telegram mentions to IRC messages

CONTRIBUTING.md, README.md
I also changed the line lengths to fit terminal better. It shouldn't
affect GitHub parsed version.
=> CONTRIBUTING.md: move PRs from README.md

src/irc/index.js
=> Handle kicks

README.md
I don't know if any other package is required.
=> Added requirements for Ubuntu to README

.eslintrc, package.json, src/index.js, src/irc/index.js
current irc dependency fails miserably when someone who isn't in the channel is unbanned
example:
00:42 -!- mode/#ghetty.space [+b *!*@nsa.gov] by prussian
00:42 -!- mode/#ghetty.space [-b *!*@nsa.gov] by prussian
would kill the bot. I changed the IRC dependency to one that I use in another bot which appears to not sporadically die.
=> New irc dependency

src/irc/index.js
=> fix for issue #196

src/irc/index.js
=> #201 fix for double messaging for events like actions and notices.

.eslintrc, src/tg/util.js
#62 
just add filler text for now. can make it "smarter" on request.
=> fix type err when replying to images #62

src/irc/index.js
=> Issue #204 - fix telegram /command 

src/irc/index.js
=> fix multiline issue.

package.json, src/config.defaults.js, src/tg/util.js
=> Web serv fix

src/irc/index.js
Fixes issue #234 by adding space before and after the `*` when sending actions.
=> Fix issue #234

src/tg/util.js
Quick fix to #217.
Can probably do better with some code refactoring, to enable reply snippets to show the beginning of the media, etc.
=> Fix <reply to image> when tg user joins/parts

src/tg/util.js
Fixes #210.
Copies behavior of replying to Telegram message.
=> Hide IRC nickname from replies
